### ISSUE TITLE
WebVR

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#14]
It is still early, but eventually regl ought to have support for WebVR.  This might require modifying the way viewports and context variables are initialized as well as how we interact with `requestAnimationFrame()`.

The current draft API is here, though it is unclear how stable it is yet:

https://w3c.github.io/webvr/

Given that VR isn't a standard yet it probably isn't worth adding VR features into regl for a 1.0.0 release, though we should make sure that whatever APIs we expose don't make it unduly difficult to write WebVR code.

A good way to make sure that things aren't screwed up would be to write a WebVR example using regl and make sure that everything works ok.

**Comment by cvan** [comment]
I saw @mikolalysenko create a repo for [`regl-stereo`](https://github.com/mikolalysenko/regl-stereo). If you need any help with hooking up `regl` (or `regl-stereo`) with the [WebVR API](https://w3c.github.io/webvr/) (with orientation, position, etc.) and [Gamepad Extensions API](https://w3c.github.io/gamepad/extensions.html) (for the VR controllers such as Oculus Touch, Oculus Remote, HTC Vive motion controllers, etc.), let me know on [Twitter at `@cvanw`](https://twitter.com/cvanw).

**Comment by rreusser** [comment]
Seems @Erkaman has tested this out with https://github.com/Erkaman/regl-webvr-demo. I could be mistaken, but seems like this might find its most natural home as a separate module.

**Comment by wwwtyro** [comment]
I've made a few demos with WebVR & regl, and I agree interfacing with it requires no changes to regl. WebVR looks like it's going to be deprecated in favor of WebXR, however, and it does appear to require some changes. See this issue: https://github.com/regl-project/regl/issues/550.

I'm going to close this, please re-open if you think I'm in error.
