### ISSUE TITLE
Need examples for GPGPU

### ISSUE THREAD

**Issue by Erkaman** [regl-project/regl#164]
Right now, there are not many examples that shows how regl can be used for GPGPU. But since regl greatly simplifies the usage of fbos, easy GPGPU is a great selling point of the framework, so we need good examples for it. Some possible examples are:

* Real-time radiosity.
* Sorting on the GPU.
* Implementations of simple GPGPU primitives, such as reduction, prefix sum, stream compaction, and so on. 
* Liquid simulation on the GPU. As can be seen in [this article](http://http.developer.nvidia.com/GPUGems/gpugems_ch38.html), this is actually not very hard to do.
* Marching Cubes

And anyone who has implemented such an example is very much welcome to submit it, by a pull request!

**Comment by mikolalysenko** [comment]
Also a few to add:

* FFT
* Sorting
* Prefix sum (rank/select)

**Comment by Erkaman** [comment]
I am currently working on implementing some GPU primitives. Right now I am working on

* Parallel Reduction 
* GPU Sorting

**Comment by Erkaman** [comment]
Parallel Reduction is done. Next is sorting.

**Comment by Erkaman** [comment]
Adding some references that may come in handy:

* Brook for GPUs: Stream Computing on Graphics Hardware
* [A Survey of General-Purpose Computation on Graphics
Hardware](https://research.nvidia.com/sites/default/files/publications/ASurveyofGeneralPurposeComputationonGraphicsHardware.pdf)
* [Building a Million Particle System - Presentation](http://www.2ld.de/gdc2004/MegaParticlesSlides.pdf)
* [Building a Million Particle System - Paper](http://www.2ld.de/gdc2004/MegaParticlesPaper.pdf)

**Comment by Erkaman** [comment]
Adding some references for implementing Deep Learning:

* [Short reference implementation in Python](https://github.com/andersbll/nnet)
* [Deep Learning Tutorial Book](http://deeplearning.net/tutorial/deeplearning.pdf)
* [Deep Learning Mit Book](http://www.deeplearningbook.org/)
* [Convolutional Neural Networks](http://cs231n.github.io/convolutional-networks/)* 
* [Conv Nets: A Modular Perspective](http://colah.github.io/posts/2014-07-Conv-Nets-Modular/)

**Comment by Erkaman** [comment]
Useful references for GPU sorting:
* [GPU gems](http://http.developer.nvidia.com/GPUGems/gpugems_ch37.html)
* [Implementation of Bitonic on GPU can be found here](http://t-pot.com/program/90_BitonicSort/index.html)

**Comment by Erkaman** [comment]
I shall give implementing deep learning a try. To do that, I will first need to implement these two components on the GPU

* Convolution
* Matrix Multiplication.

**Comment by Erkaman** [comment]
[Real time radiosity link](http://rasmusbarr.github.io/blog/realtimegi-pt2.html)

**Comment by Erkaman** [comment]
So I wrote a demo that does MNIST classification on the GPU: https://github.com/Erkaman/regl-cnn

It shows both how to implement convolution and matrix multiplication on the GPU.

**Comment by mikolalysenko** [comment]
We have some examples.  I'm gonna close this since it is too vague.

**Comment by sugeerth** [comment]
I know some existing examples  that I found useful
https://github.com/sugeerth/pycuda
