### ISSUE TITLE
Make a list of helpful tools for regl

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#185]
We should start collecting a list of modules to help out writing regl projects.  To get things started:

* [resl](https://github.com/mikolalysenko/resl)
* [glslify](https://github.com/stackgl/glslify)
* [headless-gl](https://github.com/stackgl/headless-gl)
* [regl-recorder](https://github.com/Erkaman/regl-recorder)
* [regl-stats-widget](https://github.com/Erkaman/regl-stats-widget)

**Comment by realazthat** [comment]
- [glsl-quad](https://github.com/realazthat/glsl-quad)
  - A tool/shader-generator to assist in setting up a flat 2D quad for image processing.
- [glsl-numerify](https://github.com/realazthat/glsl-numerify)
  - A tool/shader-generator to display cells with numeric color values from a texture (sometimes useful for debugging).
- [glsl-sat](https://github.com/realazthat/glsl-sat)
  - A tool/shader-generator to compute the summed area table texture of an input texture (useful for some filtering and many other algorithms).
- [glsl-gaussian](https://github.com/realazthat/glsl-gaussian)
  - A tool/shader-generator to compute the gaussian blur of an input texture, in constant time with respect to the kernel radius (though it is still just plain slow). A work in progress.
- [glsl-zoom](https://github.com/realazthat/glsl-zoom)
  - A tool/shader-generator to help show a zoom of a larger texture. Basically just adds a "zoom area" rectangle to the `glsl-quad` project, which the user can control via uniforms. Also provides much needed zoom region management (scaling, translation, clamping, bounding, keyboard => translation conversion etc.).

**Comment by mikolalysenko** [comment]
I started a list at https://github.com/mikolalysenko/awesome-regl

**Comment by Erkaman** [comment]
Anyways, with the creation of that repo, I consider this issue solved. Issue a PR to that repo if you want to add your stuff to that list.
