### ISSUE TITLE
Better camera

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#207]
Right now we are reusing canvas-orbit-camera, which is OK, but we could really be doing things much better.  At minimum we should be doing some kind of filtering on camera motion and also sampling inputs at a higher rate.

One way this camera could work is that it could define a regl command and then set up the view/projection matrices as props.  Here is a sketch of how this interface might work:

```javascript
function Camera () {
   // ... matrices, properties, configuration
}

Camera.prototype.setup = regl({
  context: {
    view: function (context, props) {
       // update camera view here
    },
    eye: function () {
      // update camera eye
    },
    inverseView: function () {
      // compute inverse view
    }
  }
})


// then to use the camera, you'd just do:
regl.frame(() => {
   camera.setup(() => {
      // now the view/projection matrices are set in the context
   })
})
```

**Comment by Erkaman** [comment]
Also, someone pointed out on reddit that with the current camera, scrolling is really slow on big screen resolutions. Our new camera should take this into account.

**Comment by mikolalysenko** [comment]
Current work in progress solution: [regl-camera](https://github.com/mikolalysenko/regl-camera)

**Comment by mikolalysenko** [comment]
Closing this issue.  Further discussion can happen in regl-camera.
