### ISSUE TITLE
Local gallery viewer

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#210]
For users who are new to budo/nodejs, it would be nice if there was an npm script that could run the gallery locally.  This could be some simple thing where you do:

```
npm run examples
```

And then it pops up a page with a list of all the examples in the gallery visible that you can click on and run.

**Comment by thammin** [comment]
Maybe we could have a fancy index page inside `www` folder which contains links to `gallery`, `compare` etc?

**Comment by mikolalysenko** [comment]
Thinking about this now, it doesn't seem like this is a great idea.  We already have a gallery that works, there's no need to be adding extra stuff.
