### ISSUE TITLE
Metaballs/implicit surface rendering demo

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#226]
Using the following modules:

* https://github.com/mikolalysenko/surface-nets
* https://github.com/mikolalysenko/isosurface

We could make some sort of interactive metaball/voxel rendering demo.

Maybe support some live editor and allow users to type in different equations.  Bonus points for doing all the computation in a worker (via webworkify for example).

**Comment by Erkaman** [comment]
Another cool thing we could do is try implementing marching cubes on the GPU.
There is a CUDA implementation in the CUDA samples provided by Nvidia, and it isn't that complicated, actually.

Although I'm not sure how easy it is to do in WebGL.

**Comment by mikolalysenko** [comment]
I've tried out some gpu accelerated implicit surface stuff, but in my experience it doesn't usually speed things up much.  That said if you have a bunch of spare vertex shader cycles and bandwidth there are a few niche applications where it can work.

**Comment by Erkaman** [comment]
The guy behind Voxel Farm says that he uses OpenCL to implement dual contouring, and I think he said that it was very necessary for achieving fast procedural generation .

**Comment by ataber** [comment]
What about rendering the implicit surfaces via raytracing? I'm interested in using `regl` for that purpose, and I'd be willing to help write an implicit surface raytracer demo to get the hang of it for my own project.

**Comment by Erkaman** [comment]
That sounds like an awesome idea! If you want to write such a demo, just go ahead and do it! If you have any problems with regl or can't figure out something, just visit the [chat](https://gitter.im/mikolalysenko/regl) and we will help you.

**Comment by ataber** [comment]
Sounds good, I'll take a stab at it!

**Comment by mikolalysenko** [comment]
Also you could use one of these modules:

* https://github.com/mikolalysenko/isosurface
* https://github.com/mikolalysenko/surface-nets

**Comment by ataber** [comment]
@mikolalysenko How about one demo for raytracing distance fields (a la http://www.iquilezles.org/www/articles/distfunctions/distfunctions.htm), and one demo polygonizing metaballs? I'd also be willing to write the polygonized metaball one.

**Comment by Erkaman** [comment]
Sounds good to me.

**Comment by Erkaman** [comment]
Implicit surfaces with raytracing added in PR #272. But a demo that renders implicit surfaces through polygonizing  the surface would also be cool.

**Comment by Erkaman** [comment]
Issue resolved as of PR #287.
