### ISSUE TITLE
Physics Simulation Example

### ISSUE THREAD

**Issue by Erkaman** [regl-project/regl#234]
We could use some open source physics engine to implement a simple physics simulation in regl. 
Or we could take it even farther, and implement a demo where you can drive a car in a heightmap. 

Does anyone have any recommendations for good physics engines in javascript?

**Comment by mikolalysenko** [comment]
The graph example is actually kind of a particle physics engine, but there is more we could do for sure.

The hard part is collision detection.  We could try using some older ideas like Takahiro Harada's voxelization methods.  There is a bunch of stuff on his home page:

* https://sites.google.com/site/takahiroharada/

The best solution though is just sparse grids + sorting, though it is tricky to do in shaders.

**Comment by Erkaman** [comment]
Yeah, but I was thinking that doing collision detection and stuff would be a bit too ambigious for a simple demo, so a library that does it on the CPU would be better.

But doing it on the GPU would also be interesting. I will take a look at those links.

**Comment by mikolalysenko** [comment]
Yeah, CPU is probably more pragmatic.  For collision detection you should use this library:

https://github.com/mikolalysenko/box-intersect

**Comment by Erkaman** [comment]
I shall see if I can figure out how integrate a physics engine with regl. And then implement a simple example.

**Comment by Erkaman** [comment]
Resolved in PR #342.
