### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by aman-tiwari** [regl-project/regl#238]
Hey,
It would be great to have typings for regl! I'm not experienced with using regl yet, but if nobody has started I can start making some as I use it more and more!

**Comment by mikolalysenko** [comment]
Yes!  I would also love to have this. If you want to add them to the main npm repo please send a PR or stop by the gitter.

**Comment by stevebest** [comment]
Progress on this: https://github.com/stevebest/regl-typings

**Comment by davschne** [comment]
I've been working on this issue the past few days, using @stevebest's work as a starting point. Hope to finish and make a PR next week. Here's what I've got: https://github.com/davschne/regl/blob/typescript-declarations/regl.d.ts
