### ISSUE TITLE
Clone takes too damn long

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#246]
Putting all the examples and having everything run from github pages has been super convenient, but there is a terrible cost.

At the moment cloning `regl` from scratch takes ~5 minutes at 160kbs, which is nuts!

We got to get this under control, ain't no one got time for that!

**Comment by realazthat** [comment]
Make a separate project for the site. Many projects do this. Also related but orthogonal would be to create a "regl" organization.

**Comment by freeman-lab** [comment]
Totally agree we need to shrink the main repo! There's a separate repo for the site at [`regl-site`](https://github.com/freeman-lab/regl-site), could move it from there into a project under a `regl` organization, so there'd be `regl/regl`, `regl/regl-site`, etc. I like that idea.

We could easily put all the example and comparison assets under the site repo, in fact, some are already copied there. And maybe even just move all the example code and example building scripts there?

This would make it slightly less convenient to rebuild the compiled examples alongside core development, but especially as things stabilize, it might be a cleaner separation for the long term.

**Comment by thammin** [comment]
Totally agree with this, it was a little confusing when we needed different node version to run the examples.

**Comment by thammin** [comment]
`git filter-branch` would be an option if you want to remove all the big files completely from the commit history. It helped me to remove some large binary files in the past and quite convenient.

Some infos: 
https://git-scm.com/docs/git-filter-branch
https://help.github.com/articles/remove-sensitive-data/

**Comment by Erkaman** [comment]
hmm, I had no idea such a command even existed. But that may possibly be the solution to our problems...

**Comment by thammin** [comment]
Example: https://github.com/thammin/regl-slimmed
Trying to remove `www` and `example` from the history and able to shrink the repo from 200+mb to 6.7mb

**Comment by Erkaman** [comment]
That sounds great!

**Comment by mikolalysenko** [comment]
We should move the www and examples folders into a separate repo.  Call it `regl-gallery` maybe?  Also those examples could be useful in other contexts like the tutorial as well.

**Comment by thammin** [comment]
Some ideas about the migration,
* clone the latest repository and remove files except examples and rename it. [regl-examples](https://github.com/regl-project/regl-examples) or `regl-gallery`?
* another clone as a backup
* remove `www` and `example` using `git filter-branch` and force push to `regl-project/regl`
* contributors re-clone the new `regl-project/regl` to their machine and done 🎉

**Comment by freeman-lab** [comment]
@mikolalysenko @thammin part of this is now done, the repo is `regl-gallery` at https://github.com/regl-project/regl-gallery and you can see that it's "working" by going here https://regl-project.github.io/regl-gallery/www/gallery.html. I preserved the git history for those bits when doing the transition, so all good there. We still need to make sure all the build scripts are working.

I'll now work on unifying the styles of our various sites. In the meantime, you could do the culling of `www` and `example` from this repo and filter as @thammin suggests, and finally bring it down to size!

**Comment by gregtatum** [comment]
Ah, this has been confusing on googling regl examples, and coming across the examples and regl-gallery page.
