### ISSUE TITLE
Example showing how to multiplex a regl context across multiple elements

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#252]
It is sometimes nice to have multiple renderable 3D views on the same page.  A naive way to do this is to give each rendered element its own canvas and webgl context, but this is usually a recipe for context loss.

Instead a better way to go would be to create one context and then multiplex it over all elements.  This large context could be placed either above/behind the elements and then masked out using transparency and viewports/scissor boxes.

**Comment by Erkaman** [comment]
With the creation of [multi-regl](https://github.com/regl-project/multi-regl), this issue is solved, so we can close, right?

**Comment by mikolalysenko** [comment]
We should add an example to the gallery still, but it is mostly solved.  Maybe we could bring in the spherical harmoncis demo from multi-regl.

**Comment by mikolalysenko** [comment]
Anyway this is done for now.  Going to close.
