### ISSUE TITLE
The future of regl

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#281]
What's the future of regl? The speed and quality of development is unprecedented. That makes wonder if regl part of a bigger project or just an experiment? Will it be done when we hit 1.0?  Are you thinking about WebGL 2?

**Comment by mikolalysenko** [comment]
At the moment regl is basically feature complete, so we are now in a phase where the main goal is to explore the API and experiment with different applications.

Things will probably evolve a bit as we learn more about the limits and capabilities of the current system, but development will stabilize. 

We've now switched to using semantic versioning and turned on code reviews which should slow down the addition of new features and breaking changes, prioritizing stability and bug fixes.

My immediate goal is to work on writing up some docs and tutorials around `regl` and to try making it simpler for people to pick up.

**Comment by Erkaman** [comment]
Well, if you got your question answered, maybe we should close this, then?
