### ISSUE TITLE
Reusing shaders

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#315]
Is there a way to reuse shaders or internal cache or treat programs like resources? I can use batch commands to render many copies of the same object but what if i have one UberShader and 1000 different meshes?

**Comment by mikolalysenko** [comment]
`regl` does this automatically.  You don't need to worry about it.

**Comment by mikolalysenko** [comment]
Also you can make attributes dynamic, just like uniforms or any other variable and then render them.  A simple way to do what you are describing would be to set up the shader using a scope or else render all your objects in batch mode.

**Comment by vorg** [comment]
Right, batch mode seems like way to go then. I can probably group objects by material and have few commands to eg. reuse texture bindings.
