### ISSUE TITLE
babelify all regl demos so they work with Safari/iOS 10

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#317]
This is just lazy, need to add those browserify transforms.

**Comment by vorg** [comment]
This required for iOS9 and Safari 9. Next version if iOS 10 supports most of ES6

**Comment by thammin** [comment]
AFAIK, Closure Compiler also supported ES6 as input language but maybe not fully covered the specs yet. 
https://github.com/google/closure-compiler/wiki/ECMAScript6
