### ISSUE TITLE
How to use depth textures

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#319]
I'm trying to use a depth texture as a depth buffer for an FBO but don't know how to make it work.

```javascript
// setup
regl = require('regl')({
    gl: gl,
    extensions: ['WEBGL_depth_texture', 'WEBGL_draw_buffers']
})
```

This works:

```javascript
 colorBuf = regl.texture({ width: win.getWidth(), height: win.getHeight() })

 fbo = regl.framebuffer({
    color: colorBuf,
    depth: true
  })
```

![screen shot 2016-09-07 at 12 21 54](https://cloud.githubusercontent.com/assets/171001/18310351/bf33fda8-74f5-11e6-8519-40d6ece88012.png)

This doesn't: 

```javascript
colorBuf = regl.texture({ width: win.getWidth(), height: win.getHeight() })

depthBuf = regl.texture({
   width: win.getWidth(),
   height: win.getHeight(),
   format: 'depth',
   type: 'uint16'
})

fbo = regl.framebuffer({
    color: colorBuf,
    depth: depthBuf
  })
```

![screen shot 2016-09-07 at 12 22 14](https://cloud.githubusercontent.com/assets/171001/18310353/c2bb1ea2-74f5-11e6-8f40-1a8180f8f458.png)

I also tried using `depthTexture` option but not sure how to access the data

```javascript
colorBuf = regl.texture({ width: win.getWidth(), height: win.getHeight() })

fbo = regl.framebuffer({
    color: colorBuf,
    depth: true,
    depthTexture: true
})
console.log(fbo.depth) // -> null
console.log(fbo.depthAttachment) // -> null
```

**Comment by vorg** [comment]
OK. Found it... after 4h

In [framebuffer.js#L308](https://github.com/regl-project/regl/blob/gh-pages/lib/framebuffer.js#L308) we are setting `DEPTH_STENCIL_ATTACHMENT` to null. That seems to be resetting `DEPTH` attachment even though   `gl.getFramebufferAttachmentParameter(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, gl.FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE)` returns `TEXTURE` (before and after commenting out).

```javascript
    attach(GL_DEPTH_ATTACHMENT, framebuffer.depthAttachment)
    attach(GL_STENCIL_ATTACHMENT, framebuffer.stencilAttachment) 
    // if i comment this out all works as expected
    // attach(GL_DEPTH_STENCIL_ATTACHMENT, framebuffer.depthStencilAttachment) 
````

From [OpenGL ES 3.0 Spec](https://www.khronos.org/opengles/sdk/docs/man3/html/glFramebufferTexture2D.xhtml) (coun't find other references as this is extension)
> Attaching a level of a texture to GL_DEPTH_STENCIL_ATTACHMENT is equivalent to attaching that level to both the GL_DEPTH_ATTACHMENT and the GL_STENCIL_ATTACHMENT attachment points simultaneously.

YaY!

<img width="792" alt="screen shot 2016-09-07 at 15 17 04" src="https://cloud.githubusercontent.com/assets/171001/18315254/378a55a0-750e-11e6-8638-40be67e7c869.png">
<img width="796" alt="screen shot 2016-09-07 at 15 16 57" src="https://cloud.githubusercontent.com/assets/171001/18315256/3aa64c8a-750e-11e6-9cd2-4923c96430b1.png">

**Question**. Any hints on debbuging regl? I ended up wrapping all gl functions to see what's happening

```javascript
  Object.keys(gl).forEach(function (key) {
    if (typeof gl[key] === 'function') {
      var fn = gl[key]
      gl[key] = function () {....
````

**Comment by Erkaman** [comment]
All created drawCommands are used to generate efficient javascript code on the fly, and it is this generated code that handles a majority  of the gl-state changes. The generated code basically looks like this:

```javascript
...
v193=v5.profile;
if(v193){
v194=performance.now();
g51.count+=a1;
}
v1.useProgram(g109.program);
var v197,v198,v199,v200,v201;
v197=g111.location;
v198=v10[v197];
if(!v198.buffer){
v1.enableVertexAttribArray(v197);
}
...
```

it is very primitive code, and reminds me a lot of assembly language, and to make it even worse, there are no variable names. Quite a while ago we were talking about writing a pretty-printer for the generated code,  but that is very low on the TODO-list, so we haven't really gotten around to it. 

So because of things like the above, debugging regl scripts can be quite tricky. But better error reporting would probably solve most of the problems(so we need to make sure to cover all edge cases in our error reporting), I think. But I usually just use the Chrome dev-tools, and set breakpoints in the scripts, and step through the code. And that has worked for me thus far.

**Comment by Erkaman** [comment]
Also, IIRC, @mikolalysenko said that he was only able to get the attachment GL_DEPTH_STENCIL_ATTACHMENT to work on both Firefox and Chrome. GL_DEPTH_ATTACHMENT and the GL_STENCIL_ATTACHMENT were buggy and did not work consistently across different browsers. And I think he left it that way, until he could figure out a solution. But maybe we should put a warning in the docs, though.

So the test cases only validate that GL_DEPTH_STENCIL_ATTACHMENT work properly, but not the other two. So for the time being, use GL_DEPTH_STENCIL_ATTACHMENT, and stay away from the other two.

**Comment by vorg** [comment]
@Erkaman I can confirm that the following works

```javascript
colorBuf = regl.texture({ width: win.getWidth(), height: win.getHeight(), alignment: 4 })

depthBuf = regl.texture({
  width: win.getWidth(),
  height: win.getHeight(),
  format: 'depth stencil', 
  type: 'depth stencil'
})

fbo = regl.framebuffer({
    color: colorBuf,
    depthStencil: depthBuf
  })
```

Still it would be goot to clarify what "GL_DEPTH_ATTACHMENT and the GL_STENCIL_ATTACHMENT were buggy and did not work consistently across different browsers" means as I'm happily living with GL_DEPTH_ATTACHMENT all my life, but maybe because i never had to use GL_STENCIL_ATTACHMENT at the same time..

**Comment by Erkaman** [comment]
Yeah, it would be great if @mikolalysenko could clarify that. Because the test cases only cover 'depth stencil' right now.

**Comment by mikolalysenko** [comment]
Sorry for the slow reply here, have been busy with driving the last few days.

This is definitely a bug in regl and it sucks that it wasted your time.  I'll take another look at depth textures and see if I can sort out what is going on with them.
