### ISSUE TITLE
Test failed with triangles drawing

### ISSUE THREAD

**Issue by thammin** [regl-project/regl#325]
```bash
⨯ drawing
not ok 4219 triangles - static
---
  operator: deepEqual
  expected: |-
    [ 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  actual: |-
    [ 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  at: runCheck (/regl/test/draw.js:48:9)
...
```

Test failed with `triangles`, `triangles strip`, and `triangles fan`.
Maybe related to https://github.com/regl-project/regl/issues/79 ? 🌾

**Comment by thammin** [comment]
My machine information:
```
OS: Mac
Graphics: AMD Radeon R9 M370X
```
Reproduced with node `0.10.33`, `4.0.0`, `6.0.0` and `Chrome`

**Comment by Erkaman** [comment]
lol, that's due to subtle diffences in the graphic cards. Getting those tests to work on both mine and Mikola's cards was a massive pain. And it seems like the pain is not over yet :(

**Comment by thammin** [comment]
Oh.. that's sad 😢 
Let's figure it out what we can do about it

**Comment by mikolalysenko** [comment]
Looks like it isn't drawing the top edge of that triangle.   Super annoying :(  We could fix this by adding some padding around the edges.

Are any other test cases failing or is it just this one?

**Comment by thammin** [comment]
The failing test cases were `triangles`, `triangles strip`, and `triangles fan`. I found that the test passed on my old non-retina Mac, maybe this is due to different drawingBuffer's size in retina display.

After some tries, found that the issue is occurred when we try to drawing on position `1 / n * k` with size of canvas as `n * n`. Like in `test/draw.js`, drawing `(-0.875, -0.875), (0.125, -0.875), (0.125, 0.125)` on `8 x 8` canvas would reproduce this.

You are right, we could fix this by adding a small padding.
`gl_Position=vec4(0.25 * (position - 3.5), 0, 1);` to `gl_Position=vec4(0.25 * (position - 3.52), 0, 1);`

**Comment by mikolalysenko** [comment]
Let me know if #332 fixes the problem

**Comment by Erkaman** [comment]
With #332, the tests still pass on my card. So nothing was broken for me. Thank god for that.
