### ISSUE TITLE
Loading extensions dynamically

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#329]
I understand that intentionally all extensions are now required to be declared during context creation as mentioned in [API.md#extensions](https://github.com/regl-project/regl/blob/gh-pages/API.md#extensions) since https://github.com/regl-project/regl/issues/7 and https://github.com/regl-project/regl/pull/80. This problematic if using libraries beyond main application entry point. e.g.

``` javascript
var Renderer = require('pex-renderer')

var regl = regl({
  gl: gl
  extensions: ['WEBGL_depth_texture']
})
var Renderer = require('pex-renderer')

// fails at framebuffer cration due to lack of OES_texture_float
var renderer = new Renderer(regl, width, height) 
```

to make it work I would need something like

``` javascript
var Renderer = require('pex-renderer')

var extensions = ['WEBGL_depth_texture'].concat(Renderer.REQUIRED_EXTENSIONS)
var regl = regl({
  gl: gl
  extensions: extensions
})

// ok, no errors
var renderer = new Renderer(regl, width, height) 
```

Ideally I would love to handle that internally in `pex-renderer` and fallback to slower or alternative paths

``` javascript
//inside pex-renderer
if (!regl.enableExtension('OES_texture_float')) {
  throw new Error('pex-renderer failed due to the lack of OES_texture_float')
})
```

Any better ideas for a pattern on how to handle this?

**Comment by mikolalysenko** [comment]
You could just enable all the extensions as optional extensions then check if they are present.

Maybe we could add wild cards to support this behavior.

**Comment by gregtatum** [comment]
I do really like the explicitness of the way extensions are enabled currently.

**Comment by vorg** [comment]
I'm going to close this. I guess the current solution is to describe the library requirements in it's README and throw an error if `regl.hasExtension()` fails on the library init.
