### ISSUE TITLE
Support offset when drawing elements

### ISSUE THREAD

**Issue by thammin** [regl-project/regl#346]
It seems like no way to pass the offset value to `drawElements`?

**Comment by mikolalysenko** [comment]
You can pass the offset flag as a property, just like count.

**Comment by thammin** [comment]
https://github.com/regl-project/regl/blob/gh-pages/API.md#drawing
Thanks! I must be missed out when checking the docs.

**Comment by thammin** [comment]
Another question, I found that we cannot pass the offset via arguments of `regl.elements`.
It would be convenient if we could do like this.
```
regl.elements({
  primitive: 'triangles',
  count: 3,
  offset: 1, // this is being ignore currently
  data: buffer,
  type: 'uint16'
})
```

**Comment by vorg** [comment]
@thammin True, we can specify `primitive` in both command and elements as default but `offset` only in command:

```javascript
var drawSomething = regl({
  elements: regl.elements({
    primitive: 'triangles', // DEFAULT
    count: 3, // DEFAULT?, not sure if that works
    offset: 1, // NOPE, this is being ignore currently
    data: buffer,
    type: 'uint16'
  }),
  count: 2, //OVERRIDE
  primitive: 'lines', //OVERRIDE
  offset: 1 //YES, this works
}
```

@mikolalysenko looks like an overlook for me

**Comment by mikolalysenko** [comment]
Yeah, this is a bug.

**Comment by mikolalysenko** [comment]
On further reflection, this is not a bug and working as intended.  There's no compelling reason for elements to track offset.
