### ISSUE TITLE
Correct API example: min or minFilter?

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#349]
Shouldn't it be `min` in [API.md#L1636](https://github.com/regl-project/regl/blame/gh-pages/API.md#L1636) ?

```javascript
// Manual mipmap specification
var mipmapTexture = regl.texture({
  minFilter: 'mipmap'
})
```

This must come from the fact that we use `min` in constructor params but `minFilter` as an internal property.

**Comment by mikolalysenko** [comment]
It should be `min`, that's a typo.
