### ISSUE TITLE
row unpack alignment

### ISSUE THREAD

**Issue by benssson** [regl-project/regl#360]
as I understand it, texture `alignment` is the unpack alignment for for pixel
e.g. below where each pixel is aligned to four bytes and padded with zeroes:

```javascript
{
      shape: [2, 2, 1],
      type: 'uint8',
      alignment: 4,
      data: new Uint8Array([1, 0, 0, 0, 2, 0, 0, 0, 
                            3, 0, 0, 0, 4, 0, 0, 0])
}
```

Is there a way of specifying the unpack alignment for the row - ie the `GL_UNPACK_ALIGNMENT`?

e.g, something like `row_alignment` below where each row is padded with zeroes:

```javascript
{
      shape: [2, 2, 1],
      type: 'uint8',
      alignment: 1,
      row_alignment: 4,
      data: new Uint8Array([1, 2, 0, 0,
                            3, 4, 0, 0])
}
```

**Comment by mikolalysenko** [comment]
Not at the moment, this is an oversight.  I'll add this in the next release.

**Comment by mikolalysenko** [comment]
Actually, WebGL doesn't support `GL_UNPACK_ROW_ALIGNMENT` so this doesn't make any sense to expose as a feature.

**Comment by benssson** [comment]
Apologies but I'm quite new to webGL. 

I've done some more digging and I'm not sure this regl is correct. I think that the texture `alignment` already actually refers to row alignment and not pixel alignment.
 
in `texture.js` line 651 the alignment is set:
```javascript
  function setFlags (flags) {
    gl.pixelStorei(GL_UNPACK_FLIP_Y_WEBGL, flags.flipY)
    gl.pixelStorei(GL_UNPACK_PREMULTIPLY_ALPHA_WEBGL, flags.premultiplyAlpha)
    gl.pixelStorei(GL_UNPACK_COLORSPACE_CONVERSION_WEBGL, flags.colorSpace)
    gl.pixelStorei(GL_UNPACK_ALIGNMENT, flags.unpackAlignment)
  }
```
and according to [https://www.khronos.org/opengles/sdk/docs/man/xhtml/glPixelStorei.xml](url) `GL_UNPACK_ALIGNMENT` is for row alignment.

In fact setting texture `alignment` to 4 and disabling line 533 in `check.js` :

```javascript
        check(img.data.byteLength === mw * mh *
          Math.max(pixelSize(img.type, c), img.unpackAlignment),
          'invalid data for image, buffer size is inconsistent with image format')
```
enables me to correctly load my bmp file that is row aligned to 4 bytes.

**Comment by mikolalysenko** [comment]
Thanks!  Looks like I got this wrong.

**Comment by mikolalysenko** [comment]
Thanks!
