### ISSUE TITLE
Shader compile errors not shown

### ISSUE THREAD

**Issue by dcposch** [regl-project/regl#361]
**Regl version: 1.2.1**

**Steps to reproduce:**
Add a compile error (for example, a missing semicolon) to some shader code.

**Expected behavior:**
Regl should log the error, eg with `console.error`. It should print the error message and line number.

**Observed:**

No information, just a runtime error about the shader program being invalid:

![image](https://cloud.githubusercontent.com/assets/169280/19093130/be41775a-8a3e-11e6-98ac-a78af5361696.png)

In this case, I could fix the shader easily, but for more complex GLSL it would be very helpful to get the compiler output if something goes wrong.

For example, you could do something like this:

```
    gl.compileShader(shader)
    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
      return console.error(gl.getShaderInfoLog(shader))
    }
```

**Comment by mikolalysenko** [comment]
What version of browserify are you using?  This behavior is seen in some older versions of browserify and is due to a bug with how options are passed to transforms.  Try updating and see if the error persists.

**Comment by dcposch** [comment]
Thx for getting back to me so quickly!

I'm pretty sure I'm on the latest version of browserify:
```
$ cat node_modules/browserify/package.json | jq .version
"13.1.0"
```

**Comment by mikolalysenko** [comment]
Second question:  Are you building your bundle using the `--debug` flag?  If you compile in release mode then regl removes all checks to reduce bundle size and runtime overhead.

**Comment by dcposch** [comment]
@mikolalysenko I am now :)

Thanks!

You might want to add a note about that here: https://github.com/regl-project/regl/blob/gh-pages/API.md

Currently that page only talks about `bin/remove-checks`

**Comment by mikolalysenko** [comment]
I am now wondering if maybe this behavior should be changed.  So far several people have complained about it.

CC @Erkaman @substack 

What do you think would be the best way to decide when to run the remove-check transform?

**Comment by Erkaman** [comment]
I think the current way it is done works. But maybe it should be documented better.

**Comment by dcposch** [comment]
@mikolalysenko yeah, I think `--debug` works well, but it would be cool to document in two places:
* The API reference: https://github.com/regl-project/regl/blob/gh-pages/API.md
* The setup instructions: https://github.com/regl-project/regl#setup

**Comment by mikolalysenko** [comment]
The docs are updated, so closing this.
