### ISSUE TITLE
Consider discontinuing support for node v0.10

### ISSUE THREAD

**Issue by asarode** [regl-project/regl#369]
Node v0.10 will stop being supported under long term support (LTS) at the end of this month. Should regl still support v0.10 or bump up to supporting everything from v0.12?

More info about the support schedule: https://medium.com/@nodejs/node-js-v6-transitions-to-lts-be7f18c17159

**Comment by mikolalysenko** [comment]
Supporting 0.10 isn't that big a deal, and isn't holding back development in any way.  Also there are still many systems using 0.10 so having this support is still nice for all those users.

As a result I don't see any upside to doing this.
