### ISSUE TITLE
Suggestion: Use monaco code editor in examples gallery

### ISSUE THREAD

**Issue by stevebest** [regl-project/regl#374]
https://github.com/Microsoft/monaco-editor

With the expected soon arrival of TypeScript typings, regl example editor could really benefit from all the features offered by Monaco editor, such as

- autocompletion,
- type inference,
- inline API documentation.

We could even build a custom syntax definition for syntax coloring of GLSL in `frag` and `vert` fields, kinda like JS/CSS embedded in HTML.

**Comment by mikolalysenko** [comment]
Cool, this issue should probably be moved over to the [regl-site repo](https://github.com/freeman-lab/regl-site) where it can get fixed.

**Comment by stevebest** [comment]
OK, closing in favor of https://github.com/freeman-lab/regl-site/issues/13
