### ISSUE TITLE
Buffer seems to add non-existent digits to float data

### ISSUE THREAD

**Issue by ataber** [regl-project/regl#375]
I'm using regl's buffer to preallocate a position array, and I'm noticing that the input has significantly fewer digits than the buffer I observe using "WebGL inspector" debugging tool.

Here's the code:
```
// Using Immutable.js to store vertices until the last moment.
const arr = vertices.toArray()
console.log(arr)
const positionBuffer = regl.buffer({
   data: arr,
   type: 'float',
   usage: 'static'
})
```
Console output:
![screen shot 2016-11-04 at 1 18 34 pm](https://cloud.githubusercontent.com/assets/1509787/20021038/656c7560-a291-11e6-83bf-8a56d69f7030.png)
WebGL Inspector output:
![screen shot 2016-11-04 at 1 18 22 pm](https://cloud.githubusercontent.com/assets/1509787/20021043/68e9fb22-a291-11e6-96c6-cd2c7b634c0e.png)

Could it be a difference as to how floats are displayed, or something more fundamental?

My model isn't displaying correctly, so I'm kind of grasping at straws to figure out why :D

**Comment by mikolalysenko** [comment]
I think that is a formatting bug.  Also GL buffer values are floating point while JS arrays are double precision, which might be causing some rounding issues.

**Comment by ataber** [comment]
Great, thanks!
