### ISSUE TITLE
Dynamic scissor test is not working

### ISSUE THREAD

**Issue by vorg** [regl-project/regl#377]
I'm trying to limit area cleared by gl.clear by using scissor test. Using object works (portion of the screen gets cleared) but using dynamic property (e.g. to get context.viewportWidth, not included in this example) fails (whole screen gets cleared)

Live version http://requirebin.com/?gist=b73a1013de503f7c7d2c00ed15e5dd8d](http://requirebin.com/?gist=b73a1013de503f7c7d2c00ed15e5dd8d)

```javascript
var regl = require('regl')()

var setupViewWorking = regl({
  scissor: {
    enable: true,
    box: {x: 0, y: 0, width: 100, height: 100}
  }
})

var setupViewNotWorking = regl({
  scissor: () => ({
    enable: true,
    box: {x: 0, y: 0, width: 100, height: 100}
  })
})

regl.frame(() => {
  regl.clear({ color: [1, 0, 0, 1] })
    setupViewWorking(() => {
    // setupViewNotWorking(() => {
      regl.clear({ color: [1, 1, 0, 1] })
    })
})
```

Expected:
![screen shot 2016-11-07 at 15 26 37](https://cloud.githubusercontent.com/assets/171001/20063375/c8664848-a4fe-11e6-8c9a-12db396d10ea.png)

What's happening if using `setupViewNotWorking`
![screen shot 2016-11-07 at 15 26 47](https://cloud.githubusercontent.com/assets/171001/20063342/afa0fa24-a4fe-11e6-8b7d-4473ae1a4109.png)

**Comment by vorg** [comment]
Actually i can make it work with replacing only scissor.box with a function. Is that expected?

```javascript
var setupViewWorkingV2 = regl({
  scissor: {
    enable: true,
    box: () => ({x: 0, y: 0, width: 100, height: 100})
  }
})
```

**Comment by mikolalysenko** [comment]
Yeah, you have to split out the properties individually.  This sucks and should be fixed.

**Comment by vorg** [comment]
I think we should split it because if we can provide whole scissor object dynamically then why not whole context object as well... etc. To much complexity. Now that i look at it its mostly matter of documentation. Alternatively there could be support for shortcuts like:

scissor
