### ISSUE TITLE
Publish 1.3.0 to npm

### ISSUE THREAD

**Issue by jwerle** [regl-project/regl#379]

**Comment by mikolalysenko** [comment]
Looks like it is already published.

**Comment by jwerle** [comment]
@mikolalysenko hmm... `1.2.1` is what [npm/regl](https://www.npmjs.com/package/regl) has. See screenshot
![](https://www.dropbox.com/s/iuj76101tkuh4cp/Screenshot%202016-11-21%2020.08.43.png?dl=1)

**Comment by jwerle** [comment]
ah interesting... this is npm failing at caching!
