### ISSUE TITLE
Inconsistent npm release versions

### ISSUE THREAD

**Issue by dcposch** [regl-project/regl#388]
The npm module version doesn't look quite right. NPM is serving `1.3.0` as the latest version, but if you go to https://npmjs.com/package/regl , it says `1.2.1` is the latest:

<img width="959" alt="screen shot 2016-12-28 at 2 02 05 am" src="https://cloud.githubusercontent.com/assets/169280/21519446/f848ff2c-cca1-11e6-9421-a4b3991f976a.png">

(Notice in the top left of this screenshot it says 1.3.0, and on the right side it says 1.2.1)

--

I also ran into an issue where `browserify` uses the full, unminified version of regl with all of the checks included, even *without* specifying `--debug`. Looks like this is fixed on the `gh-pages` branch, but not yet on npm.

Releasing a new version might fix both issues at once :)

**Comment by alvinsight** [comment]
This happened to me as well, there also doesn't seem to be any releases on github ? 
It would be good to start doing this there is a place to keep track of changes.
