### ISSUE TITLE
blend defaults

### ISSUE THREAD

**Issue by dcposch** [regl-project/regl#391]
In the API docs, it says there's a default function, so that the following *should* be equivalent:

**Works**
```
    blend: {
      enable: true,
      func: {
        src: 'src alpha',
        dst: 'one minus src alpha'
      }
    }
```

**Doesn't work**
```
    blend: {
      enable: true
    }
```

Tested with regl 1.3.0 in Chrome.

**Comment by mikolalysenko** [comment]
That's probably a documentation bug.  The defaults for src and dst should be `'one'`.

**Comment by felixfaire** [comment]
Was this reverted? It still seems to behave as ONE, ONE by default but the docs suggest alpha blending is enabled by default. See https://github.com/regl-project/regl/blob/gh-pages/API.md#blending

**Comment by pnutus** [comment]
This seems to still be a problem, tripped me up. The docs also seems to have lost the section on `props`.

I think the issue is that http://regl.party/api has not been updated to the latest `API.md` file in a _long_ while.
