### ISSUE TITLE
Ability to destroy commands

### ISSUE THREAD

**Issue by rreusser** [regl-project/regl#393]
You're not currently able to destroy commands. A workaround is to simply make attributes dynamic but for larger or longer-running processes, the ability to destroy seems necessary. Presumably `regl({...}).destroy()` would destroy a command. Are there technical hurdles like reference counting, or is this simply unimplemented?

**Comment by jwerle** [comment]
👍  this is important as there is a significant performance degradation when attributes are dynamic in a regl command. This seems to be the only way to control what is uploaded. However, I believe commands with attributes that are buffers created with `regl.buffer()` [can be destroyed](https://github.com/regl-project/regl/blob/gh-pages/API.md#buffer-destructor).

**Comment by mikolalysenko** [comment]
Makes sense.   :+1:

**Comment by fuzhenn** [comment]
Any update?

I met this problem: my draw commands are dynamically generated, and there is still no way to destroy them. 😢
