### ISSUE TITLE
Create a regl.log helper to be able to log props

### ISSUE THREAD

**Issue by alvinsight** [regl-project/regl#395]
Currently if you run: 
`console.log( regl.props('color') ` 
for example, you'll get the internal regl object, if would be good to have a `regl.log`method to give us access to this data.

**Comment by mikolalysenko** [comment]
Not quite sure what you mean.  Would you like to have some way to log the current props?  This would be possible using a function, for example:

```javascript
function loggableProp (propName) {
  return function (context, props) {
    console.log('prop: ', propName, ':', props[propName])
    return props[propName]
  }
}
```
