### ISSUE TITLE
Texture buffer?

### ISSUE THREAD

**Issue by natew** [regl-project/regl#399]
Did some searching around in code/issues but didn't see anything here. Is it possible to load textures into a buffer?

Edit: to expand on use case, looking to load array of images specifically. Continuing to search around meanwhile, will post any answer I find.

**Comment by jwerle** [comment]
@natew What kind of texture?
Have you looked at [resl](https://www.npmjs.com/package/resl)? 
Be sure to check out [example/theta360.js#L104](https://github.com/regl-project/regl/blob/gh-pages/example/theta360.js#L104)?

**Comment by mikolalysenko** [comment]
Textures and buffers are two separate things in WebGL and it isn't possible to directly copy from a texture into a buffer.  The best you could do is use read pixels and then manually set the buffer.

In WebGL 2, this would be possible using transform feedback.
