### ISSUE TITLE
missing forum

### ISSUE THREAD

**Issue by tolkanabroski** [regl-project/regl#401]
I probably the only guy who requested it. 

A forum -like "chat" with topics and really really big avatar pics for the users would be interesting. 

https://en.wikipedia.org/wiki/Internet_forum

**Comment by vorg** [comment]
There is gitter where most people involved in regl hang out http://gitter.im/mikolalysenko/regl

**Comment by tolkanabroski** [comment]
@vorg yes, i know, i suggested it mainly becourse a forum has a structure, open up new possibilities on community driven projects. Hey, i working on on SDF Raymarched Something, - ...help me with my code etc.  For now everything is kind of linear hey im working on this, and then it flops somewhere in the past of the timeline no one ever can scroll for that long to catch up a topic suggested by a user. 

For now if u a new nooby user don't have such big balls as mine, i can image a new user hesitate to ask questions becourse currently their are five guys hanging in the regl chat and all of them are hyper experienced.  
Linkto a google drive document with a heading structure 
https://goo.gl/j0qHvM

I know, that you know that im right at some point. I will mark this thread as solved after few days.
Thank you
