### ISSUE TITLE
Safari gets a JSON.parse() error on http://regl.party/examples/

### ISSUE THREAD

**Issue by avioli** [regl-project/regl#405]
Getting `JSON Parse error: Unexpected identifier "Cannot"` from `downloadedModules` when trying to `JSON.parse('Cannot GET /multi↵')`.

Browser: Safari 10.0.3
OS: macOS Sierra

Latest versions of Chrome and Firefox work on the same OS.

**Comment by rreusser** [comment]
Must be browser-module-sandbox? I get lots of CORS errors in safari:

<img width="646" alt="screen shot 2018-05-16 at 4 10 20 pm" src="https://user-images.githubusercontent.com/572717/40148597-a7f3a440-5923-11e8-8e7d-447fca9eaa57.png">

**Comment by rreusser** [comment]
Seems like a duplicate of #440, just manifesting itself in a different manner.
