### ISSUE TITLE
Invalid texture default value for colorspace conversion flag in IE11

### ISSUE THREAD

**Issue by markov00** [regl-project/regl#410]
We discovered that IE11 return a WEBGL error if the flag `GL_UNPACK_COLORSPACE_CONVERSION_WEBGL` is set to `NONE` or 0 (the default one) in textures.
I know that you can pass the colorSpace into the texture options but this is not the same if we create a FBO, that inside create a texture with default options values.

You can see this behaviour here https://codepen.io/markov00/pen/Qvajyz

What about changing the default value of colorSpace from NONE to GL_BROWSER_DEFAULT_WEBGL?

**Comment by mikolalysenko** [comment]
Looks like this got fixed in 1.3.0
