### ISSUE TITLE
some tests in test/stats-gpu.js fail

### ISSUE THREAD

**Issue by jwerle** [regl-project/regl#412]
For example, on my machine I get this intermittently:

```
not ok 37596 draw1.stats.gpuTime > draw2.stats.gpuTime after several one-shot calls
```

**Comment by mikolalysenko** [comment]
Yeah, there's a race condition in those test cases.  We need to figure out a way to harden them up or else get rid of it.

**Comment by mikolalysenko** [comment]
I am tempted to remove these test cases.  Because they're timing dependent it is difficult to reliably reproduce them.
