### ISSUE TITLE
INVALID_OPERATION when destroying a vertex attrib buffer that was used in a command

### ISSUE THREAD

**Issue by luckyxxl** [regl-project/regl#413]
Please see this minimal test: https://github.com/luckyxxl/regl/commit/1ccbbb1275ab47abb62371550b1cfaf8e7e3d0c6

When destroying a buffer that was previously used as a vertex attrib source, subsequent commands fail with a INVALID_OPERATION when they don't override the attribute in question with a new binding. This is because the WebGL vertexAttribArray state is still enabled for the attribute although the corresponding buffer has been destroyed.

I did a simple fix for my private project, but I don't think this is a good solution: https://github.com/luckyxxl/regl/commit/43c33e99eac9b5cbd4a1aaddfeca3f263a83b027

**Comment by mikolalysenko** [comment]
Thanks!

**Comment by mikolalysenko** [comment]
There should be ref counting on vertex buffers, so destroying a buffer shouldn't cause the command to fail.  I'll investigate this.

**Comment by luckyxxl** [comment]
Thank you!
