### ISSUE TITLE
regl.party fails to load in Brave 0.15.310

### ISSUE THREAD

**Issue by corderophi678** [regl-project/regl#414]
**Browser Deets:** 
Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 
libchromiumcontent: 58.0.3029.110 
V8: 5.8.283.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-53-generic 
os.arch: x64

**console output**
![screenshot_20170530_131347](https://cloud.githubusercontent.com/assets/26899349/26595570/dc1956a6-4539-11e7-89bf-425c75898e50.png)

**Comment by rreusser** [comment]
I tested this in brave@lastest on an iPhone 7 and on desktop Mac OS 10.13.4 and it works on both. I'm assuming they've long since update their js interpreter in the past year, which would certainly seem a plausible casue. Closing this issue.
