### ISSUE TITLE
Have you ever tried googling regl?

### ISSUE THREAD

**Issue by Sovairon** [regl-project/regl#415]
Hello, this is an honest issue. Did you know that regl means period in Turkish? So regl.party doesn't really bring great ideas in my mind. I'm planning to create a new project named virgin blood, what do you think?

**Comment by neiltron** [comment]
I mostly get stock market stuff related to this https://finance.yahoo.com/quote/regl
I'm in the US, though.

**Comment by mikolalysenko** [comment]
Hahaha, too late to change it now!
