### ISSUE TITLE
Attribute does not init properly after being set as constant

### ISSUE THREAD

**Issue by dfcreative** [regl-project/regl#416]
Hi @mikolalysenko!

Please consider the example (just draws points): 
```js
let regl = require('regl')()

let draw = regl({
  frag: `
  precision mediump float;
  varying vec3 fragColor;

  void main() {
    gl_FragColor = vec4(fragColor, 1);
  }`,

  vert: `
  precision mediump float;
  attribute vec2 position;
  attribute vec3 color;

  varying vec3 fragColor;

  void main() {
    gl_Position = vec4(position, 0, 1);
    gl_PointSize = 10.;
    fragColor = color;
  }`,

  attributes: {
    position: [[0, 0], [0.5, 0.5]],
    color: (ctx, props) => {
      if (props && props.color) {
        return regl.buffer(props.color)
      }
      return {constant: [0,1,0]}
    }
  },

  count: 2,

  primitive: 'points'
})


// draw different colors
draw({ color: [[0,0,1], [1,0,0]] })

// draw default color
draw()

// draw different colors later again
setTimeout(() => {
  // Here is the problem
  draw({ color: [[0,0,1], [1,0,0]] })
})
```

In the result we see green triangle rendered with constant attribute, although it is expected to display various colors.

That happens only when we draw with dynamic attribute, then reinit attribute as a constant, then again try to make it dynamic. It seems that internal state marks that attribute as constant and considers that so hereafter. Is there any workaround?

Thanks!

**Comment by dfcreative** [comment]
Also I noticed that we cannot even update constant attribute
```js
...
attributes: {
    color: (ctx, props) => {
      return {constant: props.color}
    }
  },
...

draw({ color: [0,1,0]})
draw({ color: [0,0,1] })
```
Result is rendered as `[0,1,0]`. Also if we try to `regl.clear` and then again `draw`, we don't even see the result, as if constant attribute is blocked till the end of current frame or something.

**Comment by mikolalysenko** [comment]
Weird.  This could be a bug.  Will investigate once I get on top of some client stuff.

**Comment by bpostlethwaite** [comment]
Any update on this issue? Thanks!

**Comment by mikolalysenko** [comment]
I can't reproduce this issue.  Have you tried clearing the depth buffer?  That seems to fix the problem for me.
