### ISSUE TITLE
Support for multiple render targets?

### ISSUE THREAD

**Issue by dandelany** [regl-project/regl#419]
Hi and thanks for the great library!

The `WEBGL_draw_buffers` extension allows fragment shaders to render to multiple framebuffers (render targets) by writing to `gl_FragData[0]`, `gl_FragData[1]`, etc. 

Is this/could this be supported in REGL? It would be great if the `framebuffer` option in REGL commands could take an array of `framebuffer`s.

**Comment by yoshuawuyts** [comment]
Check out https://github.com/regl-project/multi-regl and
https://github.com/substack/regl-component (:

**Comment by dandelany** [comment]
Thanks @yoshuawuyts - those look interesting!

My interest is not so much in drawing with multiple canvases/REGL instances - instead I am working on an intermediate compute shader which uses multiple `fragData` framebuffers for its *data* output - these output framebuffers will be used as inputs to the final render shader. So I'm not sure if `multi-regl` really helps with this use case in particular.

In my case I am doing a particle simulation and would like to have one fragment shader which writes to two framebuffers to keep track of 3D particle locations and velocities, respectively. The approach is similar to what this project does: https://github.com/nopjia/webgl-particles. This capability (multiple render targets) would also be useful for doing things like deferred shading - https://hacks.mozilla.org/2014/01/webgl-deferred-shading/

**Comment by grovesNL** [comment]
@dandelany This is already supported, see https://github.com/regl-project/regl/blob/gh-pages/example/deferred_shading.js

**Comment by dandelany** [comment]
Thanks very much @grovesNL - I was confused about the way framebuffers worked and didn't realize you could have multiple color attachments like that! Soooo.... nevermind :) Got things working for my use case. Thanks again for the help.
