### ISSUE TITLE
Updating 1-channel texture

### ISSUE THREAD

**Issue by dfcreative** [regl-project/regl#421]
```js
//if we have 1-channel texture 
let txt = regl.texture({channels: 1, radius: 2, data: [0, 255, 255, 0]})

//we cannot just update it's data - it throws an error
txt({data: [255, 0, 0, 255]})

//instead we have to re-initialize the texture
txt({radius: 2, channels: 1, data: [255, 0, 0, 255]})
```

Is there any sense in allowing for just updating the data, without the need to pass the whole set of options every time?

**Comment by jwerle** [comment]
@dfcreative does `texture.subimage()` not work for you? If you are just updating the data, it should work. however, if you need to change the underlying texture parameters, then a re-initialization should be required.

**Comment by dfcreative** [comment]
@jwerle it is fine for me, it just creates API inconsistency: with buffer we have useful and intuitive pattern `buffer(newData|newOptions)`, the texture is expected to behave the same way, but instead we have to read docs on how to update a texture. Not that of a big deal of course, but a bit confusing and somewhat blocks workflow.

**Comment by mikolalysenko** [comment]
calling `txt()` reinitializes the texture from scratch.  The `subimage`/`subdata` apis are meant for doing partial updates in place.  The API is currently working as intended, going to close.
