### ISSUE TITLE
Update for changes in remark, remark-lint

### ISSUE THREAD

**Issue by wooorm** [regl-project/regl#422]
Hi folks!

[`remark`](https://github.com/wooorm/remark) and [`remark-lint`](https://github.com/wooorm/remark-lint) changed a bunch since it was implemented here. Most notably, see the [`remark-lint@6.0.0`](https://github.com/wooorm/remark-lint/releases/tag/6.0.0) changelog, and the [releases for `remark`](https://github.com/wooorm/remark/releases) page to find out more.

Or, feel free to ping us on [Gitter](https://gitter.im/wooorm/remark) or below!

Cheers 👋
Titus

**Comment by mikolalysenko** [comment]
The current version of remark is working ok.  Thanks for the work, but no need to upgrade and change everything around right now.
