### ISSUE TITLE
regl status

### ISSUE THREAD

**Issue by matt-erhart** [regl-project/regl#423]
Looks like regl development has been paused since November, which is totally understandable. I'm super impressed this kind of stuff exists at all. What's the plan for regl? Is it only for people that can fix bare-metal bugs or will it be actively maintained?

**Comment by kgryte** [comment]
The project is considered complete. If there are bugs, they will be fixed.

As a general point, recency of commits is a poor indicator as to whether a project is worth using or not. Read the source, read the tests, and determine if the project suits your needs. If so, use it. If not, find something else.
