### ISSUE TITLE
Source walk-though video

### ISSUE THREAD

**Issue by matt-erhart** [regl-project/regl#424]
@mikolalysenko  Would be interesting to see a video walk-though of the source. Even just a 1-2 hour stream of consciousness screen cast would teach people a lot and probably increase/improve contributions.

**Comment by vorg** [comment]
I would love to see it as well. Not being able to fully understand the core code generation part of the library drove me away from using it on a daily basis.

**Comment by hughsk** [comment]
I've been contemplating making a PR/fork to replace the code generation with something more vanilla — have been using regl in commercial projects for a couple of months now and it's really lovely to work with for dataviz, but the black box-ness of the code generation makes me a little shy to commit to it fully.

I've found GPU to be much more of a bottleneck in practice (i.e. >10:1 GPU to CPU), so I do wonder if it makes more sense to take a bit of a performance hit for the sake of comprehension :')

**Comment by mikolalysenko** [comment]
Yeah, I'm open to the idea and have been thinking about ways to make this work.

If you want to give it a shot, go for it!

**Comment by jwerle** [comment]
@hughsk the codegen stuff is pretty powerful. It would be amazing to see it rewritten to be a bit more comprehensive, albeit, in its own module and generalized for other use cases
