### ISSUE TITLE
Missing buffer for constant attribute

### ISSUE THREAD

**Issue by dfcreative** [regl-project/regl#426]
Some check for edge-case is wrong:
```js
regl({
	frag: `
		void main() {gl_FragColor = vec4(0,0,1,1);}
	`,
	vert: `
		attribute float size;
		void main() {
			gl_Position = vec4(0,0,0,1);
			gl_PointSize = size;
		}
	`,
	primitive: 'points',
	count: 1,
	attributes: {
		size: {constant: 0}
	}
})()
```
That gives `Error: (regl) missing buffer for attribute "size"`.

**Comment by jwerle** [comment]
This looks like an error due to a truthy check, instead of a `null` or `undefined` check. It looks like [this line](https://github.com/regl-project/regl/blob/gh-pages/lib/core.js#L1648) is the culprit

**Comment by jwerle** [comment]
cc @mikolalysenko

**Comment by mikolalysenko** [comment]
@jwerle that's correct.  We should add a test case and patch this.
