### ISSUE TITLE
makepad: everything in a website done with webgl

### ISSUE THREAD

**Issue by matt-erhart** [regl-project/regl#429]
Sorry if this isn't the right place for this. Thought you all should know about it: https://www.youtube.com/watch?v=Xr6dtXw0Ipg. 
https://makepad.github.io/makepad.html

It would be awesome to just do everything with a webgl renderer, but this makepad guy doesn't want to support any open source projects. Would be awesome if some people in this community could make some of the makepad features more community driven. I know I'd like to once I'm a bit more skilled.

**Comment by gregtatum** [comment]
Cool! Looks like a fun project, but I'm not sure it's scope for regl, which is more concerned with supporting a small functional abstraction over the WebGL API. Feel free to comment back here if you drum up any ideas or projects for that.
