### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by matt-erhart** [regl-project/regl#430]
```javascript
 attributes: {
    someAttr: () => regl.buffer( array... ),
}
```
I just learned that this results in a context loss from a memory leak. I wanted to leave this here for future searchers, and understand what's happening. Why does creating the regl.buffer like the above cause a memory leak? Putting it outside the draw command works as expected.

**Comment by yoshuawuyts** [comment]
I'm not too familiar with the regl API, but from the looks of it my guess
is that the function gets called on each draw, which copies the array and
then allocates a new buffer.

Does this eventually crash tho, or does it just allocate lots of memory and
cause GC pauses?

**Comment by matt-erhart** [comment]
Creating a new regl.buffer each frame sounds right. 

Yea, it adds mbs to the ram per second crashes after 55-60 seconds and says the (regl) context was lost. Probably reaches some time/gb limit, and stops.

**Comment by jwerle** [comment]
@matt-erhart yeah returning an already created instance or just assigning the value of that attribute to be the buffer should suffice. you [can update or reinitialize the buffer later  ](https://github.com/regl-project/regl/blob/gh-pages/API.md#buffer-update). I've noticed a lot of overhead when using dynamic attributes (functions) over dynamic buffers

**Comment by gregtatum** [comment]
It appears to me you are creating WebGL buffers in a tight loop and they are not being de-allocated. There is nothing to garbage collect, as they are being added through the WebGL API, and not part of the garbage collector. This appears to be more of a user error, and nothing appears to be actionable from the side of the library, so i'm going to go ahead and close this.

**Comment by doleron** [comment]
As explained [here](https://github.com/regl-project/regl/blob/main/API.md#buffers), to avoid memory leaks, buffers must be explicitly deallocated using `buffer.destroy()`.

Note that allocating/deallocating is always costly. Then, calling `regl.buffer` (or `regl.elements`) often for each call may perform slowly. As a rule of thumb, you should allocate once and reuse your buffers as many times as needed.

If you really want to allocate your buffers on the fly, you need to release them as well. If you fail to do that, you will end up facing memory leaks and getting the browser SIGs.

A straight approach to release your buffers is tracking them, for example:
```javascript
const tracking = []
...
attributes: {
    someAttr: () => regl.buffer( array... ),
}
...
tracking.push(attributes.someAttr)
```
and then release them as follows:

```javascript
for (let buffer of tracking) {
  buffer.destroy()
}
```

Issues like this are not uncommon at all. For example, I just found this problem while playing with this code: https://github.com/jscad/OpenJSCAD.org/blob/efd7e84364792a88c30b688734f72cd5b31d3ede/packages/utils/regl-renderer/src/rendering/commands/drawMesh/index.js#L51
