### ISSUE TITLE
Do I have to update context.drawingBufferWidth/Height myself?

### ISSUE THREAD

**Issue by benwest** [regl-project/regl#431]
I've been using regl for a project and having a great time, but this bamboozled me:

`regl.frame` auto-resizes the canvas and updates `drawingBufferWidth`/`Height`, but I want to get that behaviour without `regl.frame`. There's no `regl.resize`, so I came up with this:

```javascript
var viewportCommand = regl({
    context: {
        drawingBufferWidth: regl.prop('width'),
        drawingBufferHeight: regl.prop('height')
    },
    viewport: {
        x: 0,
        y: 0,
        width: regl.prop('width'),
        height: regl.prop('height'),
    }
})

var { width, height } = element.getBoundingClientRect()

canvas.width = width
canvas.height = height

viewportCommand( { width, height }, context => {
    draw()
})
```

Is there a better way?

**Comment by jwerle** [comment]
@benwest are you creating canvas, or is regl doing it for you?

If you take a look at what is going on in the [`createCanvas()`](https://github.com/regl-project/regl/blob/gh-pages/lib/webgl.js#L5-L47) function, it'll give you an idea of how regl automatically takes care of resizing the canvas. The `drawingBufferWidth` and `drawingBufferHeight` are actually **read-only** properties on a `WebGLRenderingContext` instance and therefore setting them as context properties has no effect. You can also observe that in the [`pollViewport()`](https://github.com/regl-project/regl/blob/48abba2a32cf71af2320be811825c5e4af97f3a2/regl.js#L460) function which is actually called internally by two the functions, `regl.poll()`, and `regl._refresh()`. Calling `regl.poll()` should update the viewport and therefore the `drawingBufferWidth` and `drawingBufferHeight` context properties you care about giving you dimensions suitable for resizing the canvas.

```js
const getContext = regl.regl({})
getContext(({viewportWidth, viewportHeight, drawingBufferWidth, drawingBufferHeight}) => {
  // resize canvas as you see fit
})
```

**Comment by benwest** [comment]
Very cool, I didn't realize `regl.poll` was public. That'll do great, thanks!

**Comment by gregtatum** [comment]
This question appears to have been answered.
