### ISSUE TITLE
Integrate with react-native?

### ISSUE THREAD

**Issue by pyros2097** [regl-project/regl#437]
is it possible for regl to integrate with react-native? I've see someone integrate THREE.js to react native here https://github.com/expo/expo-three.
So was wondering if that could be done and what steps are needed to be taken?

**Comment by jwerle** [comment]
@pyros2097 While THREE is a graphics library that ships with its own renderer. regl is a webgl framework that *is* effectively a renderer. Unfortunately, there isn't an obvious way or exposed interface to provide native opengl bindings to regl

**Comment by jpweeks** [comment]
@pyros2097 Check out [`GLView`](https://docs.expo.io/versions/latest/sdk/gl-view.html). There is a [Game of Life example for REGL](https://snack.expo.io/HkjUrfIje).

**Comment by jwerle** [comment]
@jpweeks very cool! I completely forgot regl accepts a gl instance 😅

**Comment by pyros2097** [comment]
@jpweeks Thanks. Didn't see the regl example there before.
