### ISSUE TITLE
Clear up all the old build artefacts from git history

### ISSUE THREAD

**Issue by mikolalysenko** [regl-project/regl#446]
@gregtatum @dfcreative 
I'm going to finally nuke the `www/` stuff from the git history.  This will be a painful process, but when it is finished will switch the main branch to `master` from `gh-pages`.  Will leave `gh-pages` intact until we have fixed website deployments.

**Comment by gregtatum** [comment]
Sounds good. I’m getting close on the website updates, then will push on the deployment process a bit.

**Comment by mikolalysenko** [comment]
I WENT AND DID IT
