### ISSUE TITLE
Video texture example does not work

### ISSUE THREAD

**Issue by zzmp** [regl-project/regl#469]
On http://regl.party/examples, the video example does not work.

It works if you reinitialize the video every frame (`texture(video)`), but does not work with the `subimage` method, nor does it throw or log anything.

Does `subimage` not function with `HTMLVideoElement`s?

**Comment by zzmp** [comment]
This occurred on Google Chrome, Linux build, v65.0.3325.181.
It does not occur on Firefox.

I found this [old chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=380129), but it is marked as fixed. However, the [tests referenced](https://www.khronos.org/registry/webgl/conformance-suites/1.0.1/conformance/textures/tex-image-and-sub-image-2d-with-video.html) do not pass on my build.

I'm leaving this open because it affects a large browser, and makes regl look broken.
I don't expect a fix - feel free to close this once the right people have seen it.

**Comment by MaxBittker** [comment]
having the same symptoms 
(works on FF, chrome doesn't work but it does it i use `texture(video)`)

However, that test does pass for me. 

Again, it's not a regl problem, but does anyone know anything else about this bug, to help my understand it? I'd really like to find a better workaround or try to investigate a chrome fix

**Comment by MaxBittker** [comment]
this works in three.js, so we must be able to fix it!

**Comment by MaxBittker** [comment]
https://threejs.org/examples/#webgl_materials_video

**Comment by ahaoboy** [comment]
I fix this issue on my mac.
https://github.com/regl-project/regl/pull/613
