### ISSUE TITLE
Destroy draw command

### ISSUE THREAD

**Issue by fuzhenn** [regl-project/regl#481]
Related issue : #393 

Draw comand destroy is a crucial feature in many cases (including my current project). When it needs to generate commands dynamically, zoombie commands will lead to memory leaks or even crash down in the end.

So to kick off implementation, here is a launching list IMHO:

- [ ] new method: `regl({...}).destroy()` to delete generated gl program, shader, etc
- [ ] remove deleted program and shaders from local caches
- [ ] check if any cascade attribute or element buffer to destroy
  *  if a buffer is created by `regl.buffer` intentionally, NOT destroy it and leave it to user.
- [ ] test cases

Is there anything I missed? Any comment or suggestion will be highly appreciated.

**Comment by rreusser** [comment]
I'll close #393 as a duplicate since the todo list makes this a bit more actionable. 👍
