### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by rreusser** [regl-project/regl#484]
Is it reasonable to publish a new version? Anything blocking or uncertain? Perhaps 1.3.2 since—correct me if I'm wrong—there have been a number of small (but important) patches but no features added since the last publish of 1.3.1 on Jan 10.

/cc @dy @mikolalysenko

**Comment by dy** [comment]
@rreusser I hoped to finish #479 this week

**Comment by rreusser** [comment]
Glad to! Thanks. Looking into it…

**Comment by dy** [comment]
Ok, published 1.3.2 for now, since #479 is going to be a massive patch.
