### ISSUE TITLE
Question about initializing /regl/example/life.js

### ISSUE THREAD

**Issue by carlcorder** [regl-project/regl#499]
Hello,

First let me say this is an awesome project!

In reference to your [Game of Life](https://regl-project.github.io/regl/www/gallery/life.js.html) example, I was curious if anyone could give me pointers on how to initialize which cells are white?

I assume I need to fiddle with the [INITIAL_CONDITIONS](https://github.com/regl-project/regl/blob/e36bef9379b63918514c7fa7d2e5abf413634f56/example/life.js#L11):

```javascript
const RADIUS = 512
const INITIAL_CONDITIONS = (Array(RADIUS * RADIUS * 4)).fill(0).map(
() => Math.random() > 0.9 ? 255 : 0)
```

My end goal is to initialize the game with a [Sir Robin ](http://www.conwaylife.com/wiki/Sir_Robin) pattern. But I've been unsuccessful at even creating a [blinker](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life#Examples_of_patterns). Any help is appreciated!

**Comment by rreusser** [comment]
Hi! You're correct that that line in particular is what generates the initial conditions. 

Just to break it down so there's no confusion, `RADIUS` is the height and also width of the texture data it's generating. `Array(RADIUS * RADIUS * 4)` generates an empty array with enough space for r, g, b, and alpha values for each pixel (hence the 4). `Array(...).fill(0)` is a JS trick for filling a [sparse array](http://speakingjs.com/es5/ch18.html#_sparse_arrays_versus_dense_arrays) with zeros, and `.map(() => ...)` fills it in with random values—in this case 10% are 255 and 90% are zero.

I think `regl` will accept an array of four-element arrays (rgba for each pixel), so a really quick and dirty way of allowing you to set the conditions in the code might be:

```javascript
`-----
 -X---
 --X--
 ---X-
 -----`
  .replace(/[\n\s]/g,'')              // get rid of line breaks and spaces
  .split('')                          // split into single characters
  .map(c => ({'-': 0, 'X': 255}[c]))  // map -/X to 0/255
  .map(x => [x, x, x, x])             // expand to four identical components
```

This is just one way, but maybe it'll do the job. I think this might transpose or flip left/right/up/down just a bit (though there is [a `flipY` option](https://github.com/regl-project/regl/blob/master/API.md#textures) for textures). Glad to offer additional suggestions if that doesn't work, but maybe that gets the ball rolling!

Another pretty good place to ask questions might be the gitter channel: https://gitter.im/mikolalysenko/regl There's usually someone around glad to offer suggestions (often me 😬).

**Comment by carlcorder** [comment]
Thanks for your suggestions @rreusser! I will reply back in this thread if/when I get something working to share how I did it.

- All the best

**Comment by rreusser** [comment]
If it's alright I'll close this and please feel free to follow up (whether here or—even better—gitter).
