### ISSUE TITLE
Impossible parameter type "never" on regl.prop

### ISSUE THREAD

**Issue by neillrobson** [regl-project/regl#534]
Relevant line in the Typescript definition file:

https://github.com/regl-project/regl/blob/ca0a862c51622c2829a8b34ec79ed1650255185b/regl.d.ts#L139

When attempting to call `regl.prop('name')` in a TypeScript environment, the compiler infers the following type signature, rendering the method unusable:

```
REGL.Regl.prop<{}, never>(name: never): REGL.DynamicVariable<never>
```

The `never` type prevents me from passing anything in as a parameter. I am assuming that this occurs because the `Props` generic type referenced above is constrained by `extends {}`. This constraint is correct in theory, but when the `keyof` constraint is evaluated on the following generic, no keys are found and the type reduces to `never`.

For now, I suppose that I can use `// @ts-ignore` as a stop-gap measure, but having to preface every `prop` call with this comment will be tedious.

Are there any better solutions?

**Comment by neillrobson** [comment]
I found another strategy that is slightly less visually distracting. If I define the following function:

```
function reglProp<Props extends {}>(name: keyof Props) {
    return regl.prop<Props, keyof Props>(name);
}
```

I can use `reglProp("my_name")` in place of `regl.prop` and receive no TS compilation errors.

I still think that there has to be a better solution.

**Comment by nkint** [comment]
Hi! I don't really get the problem, can you give a minimum working example to test the bug?

Moreover, have you seen this example:
https://github.com/regl-project/regl/blob/master/example/typescript/dynamic.ts#L49
?

There are other for sure where `regl.prop` are used

**Comment by neillrobson** [comment]
Okay, I see the issue that I was encountering. I had never defined an interface or class to specify my props in the first place, and as such I saw no reasonable way to make the TS compiler infer that information. I was essentially doing this:

```
import * as REGL from 'regl';

const canvas = document.createElement('canvas');
document.body.appendChild(canvas);

const myProps = { name: true, aNumber: 5, ... };
const regl = REGL(canvas);

const myRegl = regl({
  ...
  uniforms: {
    name: regl.prop('name'),
    aNumber: regl.prop('aNumber),
    ...
  },
  ...
});

myRegl({
  name: myProps.name,
  aNumber: myProps.number,
  ...
});
```

Because I did not define a type for `myProps`, I had nothing to put into the angle brackets.

In the long run, I will definitely create an interface or class for my props, but as a compromise for the short term, I found that this works well:

```
const myRegl = regl({
  ...
  uniforms: {
    name: regl.prop<typeof myProp, 'name'>('name'),
    aNumber: regl.prop<typeof myProp, 'aNumber'>('aNumber),
    ...
  },
  ...
});
```

Now I just wish that the second type parameter (which, in this case, is always redundant) could be inferred by the compiler.

In any case, thank you for your help, and I apologize for cluttering the issues area with user error reports!

**Comment by jtbandes** [comment]
This is a solution I came up with that also supports things like `count: regl.prop("points.length")`:

```ts
import type REGL from "regl";

// Support nested keys like "foo.length" in regl props
type PropType<Props, Key> = Key extends `${infer K1}.${infer K2}`
  ? PropType<PropType<Props, K1>, K2>
  : Props[Key];

declare module "regl" {
  export interface Regl {
    prop<Context extends REGL.DefaultContext, Props, K extends string>(
      key: K,
    ): REGL.MaybeDynamic<PropType<Props, K>, Context, Props>;
  }
}
```
