### ISSUE TITLE
regl doesn't seem to work with OffscreenCanvas

### ISSUE THREAD

**Issue by 2xAA** [regl-project/regl#536]
Regl doesn't seem to function well in a Worker context with OffscreenCanvas, but also doesn't give any errors.

This demo shows the strange behaviour of regl when used with OffscreenCanvas.
The output on the left is from the Worker, the output on the right is from the main thread.

The code being executed is exactly the same.

https://codesandbox.io/s/static-urs19

![regl offscreeen demo](https://user-images.githubusercontent.com/554219/59399405-75265c00-8dc6-11e9-8e10-991af895ca20.gif)

**Comment by EricBalingit** [comment]
Have you tried the same code without regl?  My question is whether the offscreen canvas should be offscreen, then layered onto the onscreen canvas, which it seems it is not here.

**Comment by 2xAA** [comment]
I haven't tried, but I don't think that's necessary.
OffscreenCanvas supports the same calls as "onscreen" Canvas. There's API parity.

Drawing onto an OffscreenCanvas should "just work". The Worker has been given exclusive access to the Canvas memory space, so can draw directly to the screen without any interruption. No copying onto the "onscreen" necessary.

(2D Canvas example: https://0hgnr.codesandbox.io/)

I can throw together a non-regl demo but I'd expect something which can work in a Node environment (this was mentioned in the documentation site which no longer exists) to also work with a compatible API in a Worker also. 

But anyway, regl looks to be on hiatus/dead for now. I'm gonna transition off regl and use something else I think.

**Comment by 2xAA** [comment]
So, tried to move from regl and use something else but nothing comes close to how nice regl is to use.
Glad to see regl is active again, lots of issues with replies saying "the project is complete" I think gave me the wrong impression.

But anyway, I've investigated the issue a little and I've submitted a PR to fix this :)

Please find a working build from the PR on the [original example Code Sandbox link](https://codesandbox.io/s/static-urs19) in the OP.

**Comment by rreusser** [comment]
If you add `regl.refresh()` to the worker, it does seem to work, but that's a pretty expensive function since it resets regl's representation of the GPU state. It suggests though that something is getting out of sync, I'd suspect in the timing loop.

Do you have any better luck using `regl.frame` than `requestAnimationFrame`? I think I do, but then the problem is a bit finicky so I'm not 100% certain. Here's regl's implementation of its raf loop:

https://github.com/regl-project/regl/blob/995ed8c520e4d64beb259253598c4eb338162c32/regl.js#L149-L179

The main difference I see is `gl.flush()`, which might be worth a try, just in case something is getting triggered before the previous calls have finished. https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/flush

**Comment by rreusser** [comment]
Oh, sorry to get your hopes up. Now I'm not so sure. It seems a bit intermittent, but now it seems like `regl.frame` _doesn't_ solve it. Hmm…

**Comment by 2xAA** [comment]
@rreusser The PR I submitted earlier does seem to fix the issue.
Can you try running this? It contains a build of regl with the fix issued in the PR
https://bxptl.csb.app/

**Comment by rreusser** [comment]
Oh jeez, sorry, I missed that. Read too quickly. Looking through it…

**Comment by 2xAA** [comment]
I hadn't laid the information out properly. Just edited to clarify, my bad.

**Comment by 2xAA** [comment]
Also running the example myself, there is still an issue but seems to be intermittent/not half as bad?

Video of my experience with the "fix" here:
https://gfycat.com/spotlessaggressiveeuropeanfiresalamander

Potentially there's another step which is checking the validity of the Canvas element.
Interestingly regl wasn't throwing any error in the original example when it was being passed an "invalid" texture.
