### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jpweeks** [regl-project/regl#538]
I'm having difficulty tracking down what seems to be a fairly recent performance regression when using FBOs. I'm not sure if it's being caused by a bug in REGL or a change in browser / OS implementations of WebGL. I'm curious if any other REGL users have started noticing this issue, as I haven't seen it happen in my other Three.js projects.

The issue in my app is that CPU usage in the system profiler (macOS Activity Monitor) goes up significantly (10-15%) for each FBO that is used, which in my pipeline easily reaches full consumption of 1 thread; this happens on several different Mac laptops I've tested on in both Chrome and Safari browsers. If I disable all FBO use and draw directly to screen, CPU usage goes down to a normal low level. When CPU usage is high and I use dev tools to profile JavaScript, the flame chart looks normal with relatively low time spent scripting (~3-4ms per frame). It seems the browser is having to do a lot of work outside the scripting thread, but I'm not sure why the workload is so high, and why it seems to be related to binding FBOs. Any insight is greatly appreciated, and I will try to put together a small repro case in a day or so.

**Comment by rreusser** [comment]
I haven't noticed this, but then I don't tend to benchmark too closely. I think there was some back and forth about constructing texture data arrays full of zeros in order to silence some firefox warnings. It's suboptimal and sometimes problematic, but it's not clear to me that has any relevance here. Nothing else comes to mind. A repro would be very helpful!

**Comment by jpweeks** [comment]
I'm continuing to investigate this, but it seems the issue is a bit more convoluted.
I've created a fairly simple test case, but haven't been able to reproduce the same CPU consumption issues with it: 
> https://jsfiddle.net/jpweeks/cspwjoy7/13/

**Comment by catb0t** [comment]
The fiddle, On Linux, using discrete NVIDIA GPU, then Firefox shows almost no increase in CPU usage, and the profiler looks pretty normal.

Chrome handles it less well, and uses more CPU, but the animation is always smooth, and the CPU use is never more than 50%. 

Perhaps it's a problem with the way mac ports of browsers interface with the GPU?

**Comment by jpweeks** [comment]
@catb0t Yeah, I mentioned in my previous comment that I haven't been able to reproduce the issue with a simple test case, so it doesn't seem to be an issue specific to FBO use. I posted the current simplified test case I have and am continuing to try to isolate the issue.

Following are a couple scenes created with my engine; the only difference is one uses several blur passes while the other is rendered without any blur. The first one (with blur) uses over 90% CPU on my machine, while the second uses around 30%; this is with a 3.1GHz dual core processor. 
Has Blur Passes – https://jsfiddle.net/jpweeks/eowty9kf/
No Blur Passes – https://jsfiddle.net/jpweeks/xd5L3oet/

This drastically increased CPU load isn't recorded in dev tools for Safari or Chrome, so my guess is it has something to do with compositing or syncing state to the GPU. It seems very strange to have such a high load with nothing more than swapping frame buffers, though.

**Comment by jpweeks** [comment]
I'm making progress on identifying the issue, and it seems to be a potential bug around command scoping. In my use case I've identified a bug where some instances of scoped uniforms causes an exponential increase in `gl.*` calls: i.e. using the same command 10 times causes 100 times more state changes than using that command once.

**Comment by jpweeks** [comment]
I've created a test case of the bug, it seems to be caused by using [scoped commands](https://github.com/regl-project/regl/blob/master/API.md#scoped-commands) in combination with [batch rendering](https://github.com/regl-project/regl/blob/master/API.md#batch-rendering).

Following is the test case:
Scoped + Batched – https://jsfiddle.net/jpweeks/j2mzegnq/
Scoped + Single Draw Loops – https://jsfiddle.net/jpweeks/v1L284q7/

The two samples are identical except for the use of batched rendering, where the second example loops through the parameter sets and draws each set individually.

In the batching sample, increasing the number of iterations (`sceneItemCount`) causes a disproportional increase in `gl` state changes. i.e. for `sceneItemCount = 3` gl calls are `171` and `135` respectively; for `sceneItemCount = 100` gl calls are `63221` and `3821` respectively.

I have yet to dig into the library code to isolate the issue, I'll post back on further progress on this.

**Comment by jpweeks** [comment]
I've realized this was a bug in my own code, where I was passing the array of batch commands to both the parent command and the scoped command; not sure how I overlooked that, but here we are. 😬
