### ISSUE TITLE
About command sorting support

### ISSUE THREAD

**Issue by doodlewind** [regl-project/regl#539]
Hi, regl is very inspiring, thanks for all your great work!

I'm researching on different render libraries, and it turns out that modern projects like bgfx takes advantage of command-queue-based draw call sorting. When user performs a draw call or changes a uniform, it doesn't directly manipulate the GL state, instead the action is submitted as command into a queue, then before actual drawing, the queue is analyzed and sorted, leading to less state changes. Wondering if this is supported by regl? If it's supported, is it possible for user to modify the sort mechanism (say implement fine-grained sorting based on depth / blending state)? Thanks.

**Comment by mikolalysenko** [comment]
I thought about this, but it's tricky.  The reason is that some operations may not commute, considering depth buffer effects, blending, etc.

In the end it would be too difficult to pick a single sort order that works for all applications so instead the ordering is left to the user.
