### ISSUE TITLE
Mistake in depth stencil test

### ISSUE THREAD

**Issue by rreusser** [regl-project/regl#542]
This is not my area of expertise, but it appears this line tests nothing since `depthBuffer` is not a known [framebuffer constructor](https://github.com/regl-project/regl/blob/master/API.md#framebuffers) keyword:

https://github.com/regl-project/regl/blob/e36bef9379b63918514c7fa7d2e5abf413634f56/test/framebuffer-depth-stencil.js#L300-L305

I'm not quite able to find the right combinations of permitted keywords to make depth attachments happen just right but wanted to raise the issue in case someone does know the correct usage.

**Comment by mikolalysenko** [comment]
Good catch
