### ISSUE TITLE
Which changes where introduced in v1.5 and v1.6?

### ISSUE THREAD

**Issue by flekschas** [regl-project/regl#568]
Recently there were 2 minor version bumps: v1.5 and v1.6

Unfortunately, the [CHANGES.md](https://github.com/regl-project/regl/blob/master/CHANGES.md) does not list what has been changed. Neither do the [releases](https://github.com/regl-project/regl/releases).

I wonder what has changed in v1.5 and v1.6.

**Comment by rreusser** [comment]
Sorry about that, @flekschas! I try to help maintain and get some things out the door but had missed keeping that up to date. I'll try to help make sure it stays current. I've added all relevant details on changes since 1.4.0. https://github.com/regl-project/regl/blob/master/CHANGES.md

**Comment by flekschas** [comment]
Awesome! Thanks a lot. And no need to apologize. :)
