### ISSUE TITLE
[Q] createRegl or createREGL?

### ISSUE THREAD

**Issue by kkdd** [regl-project/regl#574]
Hello,
What is the difference between createRegl and createREGL?

**Comment by rreusser** [comment]
If using the provided bundles with an html `<script>` tag, createREGL is what's exposed in the provided, bundle. 

https://github.com/regl-project/regl/blob/ddb0e88f9c797fea9c7143c642a62505325b41a7/dist/regl.js#L4

If using it via a commonjs require or an import, then you can choose you own name and write

```js
const createRegl = require('regl')
```

and then it's really just whatever you want to call it, whether that's `createRegl` or `instantiateReGl` or something else.

**Comment by kkdd** [comment]
Thank your for your teaching me.
I have confirmed that  I can successfully choose my own name, ```createREGL``` or ```instantiateReGl```, in React's ```App.js```:

```App.js
import createREGL from "regl";
const regl = createREGL(document.querySelector('.canvas'));
```
or
```App.js
import instantiateReGl from "regl";
const regl = instantiateReGl(document.querySelector('.canvas'));
```

**Comment by rreusser** [comment]
Great! Don't hesitate to ask further questions. The gitter channel can also be a good place to get help and ask questions. Someone is usually around to help before too long: https://gitter.im/mikolalysenko/regl
