### ISSUE TITLE
Should I use regl in 2021?

### ISSUE THREAD

**Issue by AStaroverov** [regl-project/regl#598]
Hi everyone. Regl looks amazing! But, if I correct understand, maintainer isn't spending more time for this.
And now i have questions.
Are existing any count of active users this library?
Have regl enough and stable api?
Should I try regl for production?

**Comment by fuzhenn** [comment]
I'm a 2 year regl user.
The answer is yes, it's not that active because it's that stable.
So you can use it for production for sure.

**Comment by rreusser** [comment]
I also use it all the time, personally and (previously) professionally. I don't know a count, but I think it's found its way into a number of commercial products. As @fuzhenn says, regl's goal is to wrap the WebGL API to solve state management and provide just a couple small additional conveniences. Anything beyond that probably belongs in a third party library (http://stack.gl/ has a lot of modules that work well with regl, though they don't have any dependence on regl itself). So in that sense, it's relatively close to complete and gets mostly occasional small bug fixes or small features.

I'd definitely recommend using it! The [regl gallery](https://regl-project.github.io/regl/www/gallery.html) was very helpful for me, and [the gitter forum](https://gitter.im/mikolalysenko/regl) is a bit quiet these days, but someone usually stops by who can help.

**Comment by AStaroverov** [comment]
Thx for the answers, now it's clear to me :)
