### ISSUE TITLE
why the callback function still be called after the cancellation?

### ISSUE THREAD

**Issue by jcyuan** [regl-project/regl#599]
hi guys, this is my code snippet:

```typescript
this._ticker = this._regl.frame(this.update.bind(this));
update() {
      console.log("draw...");
      this._cmd.draw(this._props);
      if (theProgressIsComplete && destroyNotCalled) {
             this._ticker.cancel();
             this._cmd.destroy();
             console.log("after destroy...");
             destroyNotCalled = false;
      }
}
```

as you can see:
![image](https://user-images.githubusercontent.com/850854/106844287-13291180-66e3-11eb-8d58-d5f1ca5161a8.png)

even i call the `cancel` method, the `update` function is still called extra once... why? how can i solve this?
thanks.

**Comment by rreusser** [comment]
Interesting. I haven't seen this. I can't imagine there's any way you've accidentally called `regl.frame` more than once? I see this note:

https://github.com/regl-project/regl/blob/f95aac9786d2a09acd37fbd45a6c5f6428620d20/regl.js#L460-L461

But it's certainly possible there's a small bug hiding somewhere. If you're able to boil it down to a reproducible test case, I'm glad to take a closer look.

**Comment by jcyuan** [comment]
ok, a moment, going to make a test case.

**Comment by jcyuan** [comment]
@rreusser hi, i'm so sorry.... that's a bug caused by my eventdispatcher.... `Cancellable.cancel()` works just fine!!

**Comment by jcyuan** [comment]
@rreusser  HI, I'm so sorry, that's caused by my event triggering sequence... i called `destroy` in a callback but after that i still called `draw()` without check if `regl` is destroied.
`Cancellable.cancel` works just fine! thanks so much!
