### ISSUE TITLE
Alpha blending with framebuffer rendering does not work in Safari 14 

### ISSUE THREAD

**Issue by flekschas** [regl-project/regl#619]
I noticed that in Safari 14, alpha blending is broken when used in combination with framebuffer rendering. Alpha blending and framebuffer rendering (without alpha blending) works as expected. Interestingly, alpha blending + framebuffer rendering works just fine in Safari 13 as well as all other major browsers (tested it in Chrome, Edge, and Firefox), which makes me wonder if Safari 14 is just broken or if there is an issue with Regl.

**Demo:** https://jsfiddle.net/flek/rc6zbk0d/58/

It _should_ look as follows:
![May-21-2021 17-57-29](https://user-images.githubusercontent.com/932103/119202116-29729780-ba5e-11eb-8230-e768ed3f34a8.gif)

However, in Safari 14 the _purple triangle+dots are never rendered_.

My alpha blending is nothing fancy:

```js
blend: {
  enable: true,
  func: {
    srcRGB: 'src alpha',
    srcAlpha: 'src alpha',
    dstRGB: 'one minus src alpha',
    dstAlpha: 'one minus src alpha',
  },
},
```

The framebuffer is a float texture and the `OES_texture_float` extension is activated.

```js
const fbo = regl.framebuffer({
  width: res[0],
  height: res[1],
  colorFormat: 'rgba',
  colorType: 'float',
});
```

Has anyone else experience this or an idea whether this is an issue with Safari 14, regl, or my code?

**Comment by rreusser** [comment]
Hmm… seems suspicious. Just a thing or two:

This pattern:

```js
const drawTriangle = (color = [1, 0, 0, 1]) => {
  regl({
    ...
    uniforms: {
      color: () => color
    }
  })
}
```

is *very* inefficient, as it recreates the WebGL command every time it's used (includes compiling the shader). Instead, this pattern using `regl.prop` is equivalent:

```js
const drawTriangle =  regl({
  ...
  uniforms: {
    color: regl.prop('color')
  }
})
```

or even closer, if you prefer a default:


```js
const drawTriangle =  regl({
  ...
  uniforms: {
    color: (ctx, props) => props.color === undefined ? [1, 0, 0, 1] : props.color
  }
})
```

Also, you may need to call `regl.poll()` if using your own timing loop and not `regl.frame()`. See: https://github.com/regl-project/regl/blob/master/API.md#per-frame-callbacks

Agreed that something seems suspicious, but I think first we need to rule out a couple other possibilities.

**Comment by flekschas** [comment]
Good catch regarding the efficiency! I haven't really paid attention to that as I was just trying to find out what combination of features results in Safari 14 failing to render anything.

**Comment by flekschas** [comment]
I found the fix. Or I should rather say, Firefox came to the rescue by printing some warnings into the console!

Apparently Safari 14 changed the way extensions were loaded. Previously, when `OES_texture_float` was activated, the `EXT_float_blend` extension was activated as well. Which is also what's described on MDN if I understand it correctly:

> On devices that support the EXT_float_blend extension, it is automatically, implicitly, enabled when any one or more of EXT_color_buffer_float, OES_texture_float, or WEBGL_color_buffer_float are enabled. This ensures that content written before EXT_float_blend was exposed by WebGL will function as expected.

_Source: https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend#usage_notes_

However, this does not seem to be the case anymore. So one must manually activate `WEBGL_color_buffer_float` and then `EXT_float_blend`.

Here is the very same demo from above with the two extensions explicitly activated and now it works in Safari 14 as expected 🎉

**Working demo:** https://jsfiddle.net/5joqkugd/
