### ISSUE TITLE
Buffers with mixed data types

### ISSUE THREAD

**Issue by schroffl** [regl-project/regl#634]
Hello :)

First of all I wanna say that I really enjoy using this library. It gives me a feeling of native WebGL all the while removing lots of management overhead and being a joy to use.

There's one thing I was wondering: How does regl handle buffers that contain different data types? 
Let's say I have a buffer of entities where each one consists of a 2D position and an index into a sprite atlas.

```javascript
const array_buffer = new ArrayBuffer(9);
const view = new DataView(array_buffer);

// Entity of type `3` at position (`20.2`, `73.7`)
view.setFloat32(0, 20.2);
view.setFloat32(4, 73.7);
view.setUint8(8, 3);
```

With raw WebGL you would be able to do this:
```javascript
const buf = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
gl.bufferData(gl.ARRAY_BUFFER, array_buffer, gl.STATIC_DRAW);

// Other setup left out for clarity...

gl.vertexAttribPointer(pos_location, 2, gl.FLOAT, false, 9, 0);
gl.vertexAttribPointer(sprite_location, 1, gl.UNSIGNED_BYTE, false, 9, 8);

// Draw
```

However, I'm not sure how to translate this to regl:
```javascript
const buf = regl.buffer({
    data: array_buffer,
    type: 'float', // but it's not all floats (?)
    usage: 'static',
});

const draw = regl({
    vert: '[...]',
    frag: '[...]',
    attributes: {
        position: {
            buffer: buf,
            stride: 9,
            offset: 0,

            // Should it be possible to specify a type per attribute?
        },
        sprite: {
            buffer: buf,
            stride: 9,
            offset: 8,
        },
    },
});
```

[This line of code in `lib/attributes.js`](https://github.com/regl-project/regl/blob/104e83225336666d29f5d2a6534e837d3b6f5f04/lib/attribute.js#L119) (and [another one](https://github.com/regl-project/regl/blob/104e83225336666d29f5d2a6534e837d3b6f5f04/lib/attribute.js#L170)) seems to suggest that a regl buffer can only house data of _one_ type.
I'm not really sure about all of this, because I don't know the codebase. Maybe I am missing something... Am I?

**Comment by rreusser** [comment]
Good question! Actually this looks like a major omission in regl's [attribute specification](https://github.com/regl-project/regl/blob/master/API.md#attributes). I made a notebook here that illustrates use of `type` to accomplish this. For example, imagine float32 x, y, z with uint8 rgba, totaling 16 bytes:

https://observablehq.com/d/3c5584380a5a42a4

```
byte: 0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
    +---------------+---------------+---------------+---+---+---+---+
    |       x       |       y       |       z       | r | g | b | a | 
    +---------------+---------------+---------------+---+---+---+---+
```

Packing the data into a single buffer, you can hook this up to attributes as:

```js
  attributes: {
    position: {
      buffer: dataBuffer,
      offset: 0,
      stride: 16,
      type: "float"
    },
    color: {
      buffer: dataBuffer,
      offset: 12,
      stride: 16,
      normalized: true,
      type: "uint8"
    }
  },
```

**Comment by schroffl** [comment]
@rreusser Thanks a lot! :)
