### ISSUE TITLE
Live reloading shaders?

### ISSUE THREAD

**Issue by jeffawang** [regl-project/regl#643]
Is it possible to swap the shader program being used by a `regl` instance?

I'm aware it's possible to do hot reloading of everything at build time, but I'd like to make a collaborative live editor, which will require runtime updating with user-provided code. As a result, the shader should be updated frequently, often with non-compiling code.

Currently I'm making a new `regl` instance per keystroke. Is this the best practice right now?

**Comment by rreusser** [comment]
You can write write:

```js
draw = regl({
  vert: regl.prop('vert'),
  frag: regl.prop('frag'),
  ...
})
```

and then call it with

```js
draw({ vert: myVertSource, frag: myFragSource })
```

On each call it will do a string comparison of the source and only recompile if the source has changed. Relatively speaking, it should be quite performant.

Just to double-check I wasn't giving bad advice, I made a notebook here to demonstrate: https://observablehq.com/d/79823713d23613cd
