### ISSUE TITLE
online examples/playground broken (regl.party)

### ISSUE THREAD

**Issue by fr-an-k** [regl-project/regl#666]
http://regl.party/examples does not work due to modern security policies; it should be HTTPS and have CORS configured.

**Comment by kevzettler** [comment]
prob duplicate of https://github.com/regl-project/regl/issues/615

**Comment by kevzettler** [comment]
@fr-an-k do you remember where you found that link to the examples? The examples link on http://regl.pary homepage links to: 

https://regl-project.github.io/regl/www/gallery.html

Which is the modern example gallery

**Comment by fr-an-k** [comment]
From the regl documentation:
See this example [live](http://regl.party/examples/?basic)

It might be on search engines as well. I'm guessing regl.party should be https and the example server should allow the regl.party origin.

**Comment by rreusser** [comment]
I'm going to close this, as there's no plan to resurrect the live editor. It may not suit everyone's tastes, but I really like Observable for experimenting with regl and made a helper here to create a canvas: https://observablehq.com/@rreusser/regl-canvas

Other code editors like codepen (using https://unpkg.com/regl ) should be perfectly adequate.
