### ISSUE TITLE
Need to run unit tests for non-debug builds as well.

### ISSUE THREAD

**Issue by Erkaman** [regl-project/regl#88]
Right now, the unit tests are only run for the debug versions of the tests, that is, with all the checks. 
But it would be good to also run the unit tests for non-debug versions of the tests, that is, without all the checks. Sometimes bugs can otherwise slip through, as was seen in PR #85.

**Comment by mikolalysenko** [comment]
One problem with this is that in some of the test cases explicitly test the check behavior.  If we remove the checks in release mode then those tests would fail.

It isn't clear to me that we need to support this right now.

**Comment by Erkaman** [comment]
Yeah, it seems tricky to implement.

**Comment by Erkaman** [comment]
So close
